<?php
$month=(string)($_GET['month']??date('Y-m'));if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$month))$month=date('Y-m');
$scope=(string)($_GET['scope']??'store');if(!in_array($scope,['store','dapur'],true))$scope='store';
$user=bo_user()??[];$uid=(int)($user['id']??0);$canWrite=in_array(strtolower((string)($user['role_key']??'')),['owner','admin'],true);
function bo_att_table_exists(string $t): bool {try{return (int)bo_exec('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?',[$t])->fetchColumn()>0;}catch(Throwable $e){return false;}}
function bo_att_csrf(): string {bo_session_start();if(empty($_SESSION['bo_att_csrf']))$_SESSION['bo_att_csrf']=bin2hex(random_bytes(24));return (string)$_SESSION['bo_att_csrf'];}
function bo_att_check_csrf(): void {bo_session_start();$v=(string)($_POST['csrf']??'');if($v===''||empty($_SESSION['bo_att_csrf'])||!hash_equals((string)$_SESSION['bo_att_csrf'],$v))throw new RuntimeException('Sesi formulir tidak valid.');}
function bo_att_redirect(string $scope,string $month,string $notice='',string $type='ok'): never {$q=['p'=>'attendance','scope'=>$scope,'month'=>$month];if($notice!==''){$q['notice']=$notice;$q['notice_type']=$type;}header('Location:?'.http_build_query($q));exit;}
$ready=bo_att_table_exists('bo_attendance_period_settings')&&bo_att_table_exists('bo_attendance_entries');
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  if(!$canWrite)throw new RuntimeException('Akses tulis hanya untuk Owner/Admin.');if(!$ready)throw new RuntimeException('SQL absensi belum diimpor.');bo_att_check_csrf();
  $action=(string)($_POST['action']??'');$ps=(string)($_POST['scope']??$scope);if(!in_array($ps,['store','dapur'],true))throw new RuntimeException('Kelompok absensi tidak valid.');
  if($action==='save_attendance'){
   $target=(float)str_replace(',','.',(string)($_POST['target_workdays']??0));if($target<0)throw new RuntimeException('Target hari kerja tidak boleh negatif.');
   bo_exec("INSERT INTO bo_attendance_period_settings(attendance_month,scope_key,target_workdays,created_by,updated_by,created_at) VALUES(?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE target_workdays=VALUES(target_workdays),updated_by=VALUES(updated_by),updated_at=NOW()",[$month,$ps,$target,$uid,$uid]);
   foreach((array)($_POST['attended_days']??[]) as $assignmentId=>$days){$assignmentId=(int)$assignmentId;if($assignmentId<=0)continue;$days=(float)str_replace(',','.',(string)$days);if($days<0)throw new RuntimeException('Jumlah kehadiran tidak boleh negatif.');if($target>0&&$days>$target)throw new RuntimeException('Kehadiran tidak boleh melebihi target hari kerja.');$note=trim((string)(($_POST['notes']??[])[$assignmentId]??''));bo_exec("INSERT INTO bo_attendance_entries(attendance_month,scope_key,assignment_id,attended_days,notes,created_by,updated_by,created_at) VALUES(?,?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE scope_key=VALUES(scope_key),attended_days=VALUES(attended_days),notes=VALUES(notes),updated_by=VALUES(updated_by),updated_at=NOW()",[$month,$ps,$assignmentId,$days,$note,$uid,$uid]);}
   bo_att_redirect($ps,$month,'Absensi dan target hari kerja disimpan.');
  }
  throw new RuntimeException('Aksi tidak dikenali.');
 }catch(Throwable $e){bo_att_redirect($scope,$month,$e->getMessage(),'err');}
}
$csrf=bo_att_csrf();$notice=(string)($_GET['notice']??'');$noticeType=(string)($_GET['notice_type']??'ok');
$target=0.0;$entries=[];$rows=[];
if($ready){$v=bo_exec('SELECT target_workdays FROM bo_attendance_period_settings WHERE attendance_month=? AND scope_key=? LIMIT 1',[$month,$scope])->fetchColumn();$target=$v!==false?(float)$v:0.0;$er=bo_exec('SELECT assignment_id,attended_days,notes FROM bo_attendance_entries WHERE attendance_month=? AND scope_key=?',[$month,$scope])->fetchAll()?:[];foreach($er as $e)$entries[(int)$e['assignment_id']]=$e;$source=$scope==='dapur'?'dapur':'adena';$rows=bo_exec("SELECT a.id assignment_id,a.system_name,a.role_key,a.location,p.canonical_name FROM bo_employee_assignments a JOIN bo_employee_people p ON p.id=a.person_id WHERE a.is_active=1 AND p.is_active=1 AND p.manually_disabled=0 AND LOWER(TRIM(COALESCE(a.source_system,'')))=? AND LOWER(TRIM(COALESCE(a.role_key,''))) NOT IN ('owner','superadmin') ORDER BY a.system_name,p.canonical_name",[$source])->fetchAll()?:[];}
?>
<style>.att-nav{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.attendance-table input[type=number]{width:110px}.attendance-table input[type=text]{min-width:220px}</style>
<div class="page-title"><div><h1>Absensi SDM</h1><div class="muted">Absensi Toko dan Dapur dipisahkan. Kehadiran diinput manual per pegawai dan target hari kerja berlaku untuk seluruh pegawai pada kelompok/periode yang dipilih.</div></div></div>
<?php if($notice!==''): ?><div class="alert <?=$noticeType==='err'?'danger':'ok'?>"><?=e($notice)?></div><?php endif; ?>
<?php if(!$ready): ?><div class="alert danger">Import <b>db/20260915_008_attendance_dapur_incentive_bo_region.sql</b> terlebih dahulu.</div><?php endif; ?>
<div class="att-nav"><a class="btn <?=$scope==='store'?'primary':''?>" href="?p=attendance&scope=store&month=<?=e($month)?>">Absensi Pegawai Toko</a><a class="btn <?=$scope==='dapur'?'primary':''?>" href="?p=attendance&scope=dapur&month=<?=e($month)?>">Absensi Pegawai Dapur</a></div>
<div class="card"><div class="section-head"><div><h3><?=e($scope==='dapur'?'Absensi Pegawai Dapur':'Absensi Pegawai Toko')?> — <?=e($month)?></h3><div class="muted">Target hari kerja diinput satu kali dan berlaku ke semua pegawai pada tabel ini.</div></div><form class="filters" method="get"><input type="hidden" name="p" value="attendance"><input type="hidden" name="scope" value="<?=e($scope)?>"><label>Periode<input type="month" name="month" value="<?=e($month)?>"></label><button class="btn primary">Tampilkan</button></form></div>
<?php if($ready): ?><form method="post"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="save_attendance"><input type="hidden" name="scope" value="<?=e($scope)?>"><div style="max-width:260px;margin:10px 0 16px"><label><b>Target Hari Kerja (semua pegawai)</b><input type="number" min="0" step="0.5" name="target_workdays" value="<?=e($target)?>" <?=$canWrite?'':'disabled'?>></label></div><div class="table-wrap attendance-table"><table><thead><tr><th>Pegawai</th><th>Unit</th><th>Role</th><th>Jumlah Hadir</th><th>Target</th><th>Catatan</th></tr></thead><tbody><?php foreach($rows as $r): $en=$entries[(int)$r['assignment_id']]??[]; ?><tr><td><b><?=e($r['canonical_name'])?></b></td><td><?=e($r['system_name'])?></td><td><?=e($r['role_key'])?></td><td><input type="number" min="0" step="0.5" name="attended_days[<?=$r['assignment_id']?>]" value="<?=e($en['attended_days']??0)?>" <?=$canWrite?'':'disabled'?>></td><td><?=e(number_format($target,2,',','.'))?></td><td><input type="text" name="notes[<?=$r['assignment_id']?>]" value="<?=e($en['notes']??'')?>" <?=$canWrite?'':'disabled'?>></td></tr><?php endforeach;if(!$rows): ?><tr><td colspan="6">Belum ada pegawai aktif pada kelompok ini.</td></tr><?php endif; ?></tbody></table></div><?php if($canWrite): ?><div class="section"><button class="btn primary">Simpan Absensi</button></div><?php endif; ?></form><?php endif; ?>
</div>
