<?php
require_once __DIR__.'/../core/OperationalSummary.php';
$month=$_GET['month']??date('Y-m');if(!preg_match('/^\d{4}-\d{2}$/',$month))$month=date('Y-m');
$stores=bo_ops_fetch_summaries('adena',$month);$kitchens=bo_ops_fetch_summaries('dapur',$month);$rows=[];$errors=[];
foreach($stores as $u){if(!$u['ok']){$errors[]=$u['name'].': '.$u['message'];continue;}$d=$u['data'];$rows[]=['unit'=>$u['name'],'type'=>'Toko Penerima','pending'=>bo_ops_num(bo_ops_first($d,[['distribution','pending'],'pending_distributions'],0)),'received'=>bo_ops_num(bo_ops_first($d,[['distribution','received'],'distribution_received'],0)),'returned'=>bo_ops_num(bo_ops_first($d,[['distribution','returned'],'distribution_returned'],0)),'failed'=>bo_ops_num(bo_ops_first($d,[['distribution','failed'],'distribution_failed'],0)),'value'=>0];}
foreach($kitchens as $u){if(!$u['ok']){$errors[]=$u['name'].': '.$u['message'];continue;}$d=$u['data'];$rows[]=['unit'=>$u['name'],'type'=>'Dapur Pengirim','pending'=>bo_ops_num(bo_ops_first($d,[['distribution','sent'],'pending_distributions'],0)),'received'=>bo_ops_num(bo_ops_first($d,[['distribution','received']],0)),'returned'=>bo_ops_num(bo_ops_first($d,[['distribution','cancelled']],0)),'failed'=>bo_ops_num(bo_ops_first($d,[['distribution','failed']],0)),'value'=>bo_ops_num(bo_ops_first($d,['kitchen_revenue_month','dapur_omset_month'],0))];}
$storePending=0;$storeReceived=0;$storeReturned=0;$kitchenSent=0;$kitchenReceived=0;$kitchenFailed=0;foreach($rows as $r){if($r['type']==='Toko Penerima'){$storePending+=$r['pending'];$storeReceived+=$r['received'];$storeReturned+=$r['returned'];}else{$kitchenSent+=$r['pending'];$kitchenReceived+=$r['received'];$kitchenFailed+=$r['failed'];}}
?>
<div class="page-title"><div><h1>Distribusi</h1><div class="muted">Status pengiriman dapur dan konfirmasi penerimaan toko.</div></div></div>
<form class="filters"><input type="hidden" name="p" value="distribution"><div><label>Periode</label><input type="month" name="month" value="<?=e($month)?>"></div><div><button class="btn primary">Filter</button></div></form>
<div class="grid"><div class="card metric"><div class="label">Pending di Toko</div><div class="value"><?=e((int)$storePending)?></div></div><div class="card metric"><div class="label">Terkirim dari Dapur</div><div class="value"><?=e((int)$kitchenSent)?></div></div><div class="card metric"><div class="label">Diterima Toko</div><div class="value"><?=e((int)$storeReceived)?></div></div><div class="card metric"><div class="label">Dikembalikan Toko</div><div class="value"><?=e((int)$storeReturned)?></div></div><div class="card metric"><div class="label">Gagal Sinkron Dapur</div><div class="value"><?=e((int)$kitchenFailed)?></div></div></div>
<div class="table-wrap section"><table><thead><tr><th>Unit</th><th>Peran</th><th>Pending</th><th>Diterima</th><th>Dikembalikan/Dibatalkan</th><th>Gagal</th><th>Nilai Transfer Bulan Ini</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><b><?=e($r['unit'])?></b></td><td><?=e($r['type'])?></td><td><?=e((int)$r['pending'])?></td><td><?=e((int)$r['received'])?></td><td><?=e((int)$r['returned'])?></td><td><?=e((int)$r['failed'])?></td><td><?=money_id($r['value'])?></td></tr><?php endforeach;if(!$rows): ?><tr><td colspan="7">Belum ada data distribusi.</td></tr><?php endif; ?></tbody></table></div>
<div class="card section"><b>Catatan konsolidasi:</b> nilai transfer dapur ke toko adalah transaksi internal. Nilainya relevan untuk margin per unit, tetapi harus dieliminasi saat menghitung profit seluruh Adena.</div>
<?php if($errors): ?><div class="card section"><h3>Catatan API</h3><?php foreach($errors as $err): ?><div class="alert danger"><?=e($err)?></div><?php endforeach; ?></div><?php endif; ?>
