<?php
require_once __DIR__.'/../core/OperationalSummary.php';

$section=(string)($_GET['section']??'overview');
$allowed=['overview','store_master','store_input','store_recap','dapur','backoffice_master','backoffice_input','backoffice_recap'];
if(!in_array($section,$allowed,true))$section='overview';
$month=(string)($_GET['month']??date('Y-m'));if(!preg_match('/^\d{4}-\d{2}$/',$month))$month=date('Y-m');
$user=bo_user()??[];$uid=(int)($user['id']??0);$canWrite=in_array(strtolower((string)($user['role_key']??'')),['owner','admin'],true);

function bo_kpi_table_exists(string $table): bool {try{$st=bo_exec('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?',[$table]);return (int)$st->fetchColumn()>0;}catch(Throwable $e){return false;}}
function bo_kpi_csrf(): string {bo_session_start();if(empty($_SESSION['bo_kpi_csrf']))$_SESSION['bo_kpi_csrf']=bin2hex(random_bytes(24));return (string)$_SESSION['bo_kpi_csrf'];}
function bo_kpi_check_csrf(): void {bo_session_start();$v=(string)($_POST['csrf']??'');if($v===''||empty($_SESSION['bo_kpi_csrf'])||!hash_equals((string)$_SESSION['bo_kpi_csrf'],$v))throw new RuntimeException('Sesi formulir tidak valid.');}
function bo_kpi_redirect(string $section,string $month,string $notice='',string $type='ok'): never {$q=['p'=>'kpi','section'=>$section,'month'=>$month];if($notice!==''){$q['notice']=$notice;$q['notice_type']=$type;}header('Location:?'.http_build_query($q));exit;}
function bo_kpi_scope_from_section(string $section): string {return str_starts_with($section,'backoffice_')?'backoffice':'store';}
function bo_kpi_master_rows(string $scope,bool $activeOnly=false): array {$sql='SELECT * FROM bo_kpi_masters WHERE scope_key=?'.($activeOnly?' AND is_active=1':'').' ORDER BY sort_order,kpi_name';return bo_exec($sql,[$scope])->fetchAll()?:[];}
function bo_kpi_weight_total(string $scope): float {$st=bo_exec('SELECT COALESCE(SUM(weight),0) FROM bo_kpi_masters WHERE scope_key=? AND is_active=1',[$scope]);return (float)$st->fetchColumn();}
function bo_kpi_store_employees(): array {return bo_exec("SELECT a.id assignment_id,a.person_id,a.system_key,a.system_name,a.external_employee_id,a.role_key,p.canonical_name FROM bo_employee_assignments a JOIN bo_employee_people p ON p.id=a.person_id WHERE a.is_active=1 AND p.is_active=1 AND p.manually_disabled=0 AND LOWER(TRIM(COALESCE(a.source_system,'')))<>'dapur' AND LOWER(TRIM(COALESCE(a.role_key,''))) NOT IN ('owner','superadmin') ORDER BY a.system_name,p.canonical_name")->fetchAll()?:[];}
function bo_kpi_admin_employees(): array {return bo_exec("SELECT id bo_user_id,name,username,role_key FROM bo_users WHERE is_active=1 AND LOWER(TRIM(role_key))='admin' ORDER BY name")->fetchAll()?:[];}
function bo_kpi_find_assessment(string $scope,string $month,int $assignmentId,int $boUserId): ?array {$sql='SELECT * FROM bo_kpi_assessments WHERE scope_key=? AND assessment_month=? AND '.($scope==='store'?'assignment_id=?':'bo_user_id=?').' LIMIT 1';$r=bo_exec($sql,[$scope,$month,$scope==='store'?$assignmentId:$boUserId])->fetch();return $r?:null;}
function bo_kpi_build_assessment(string $scope,string $month,int $assignmentId,int $boUserId,int $uid): int {
 $a=bo_kpi_find_assessment($scope,$month,$assignmentId,$boUserId);if($a)return (int)$a['id'];
 $systemKey='backoffice';$systemName='Back Office';
 if($scope==='store'){$r=bo_exec('SELECT system_key,system_name FROM bo_employee_assignments WHERE id=? LIMIT 1',[$assignmentId])->fetch();if(!$r)throw new RuntimeException('Pegawai toko tidak ditemukan.');$systemKey=(string)$r['system_key'];$systemName=(string)$r['system_name'];}
 bo_exec('INSERT INTO bo_kpi_assessments(scope_key,assessment_month,assignment_id,bo_user_id,system_key,system_name,status,final_score,total_weight,created_by,created_at) VALUES(?,?,?,?,?,?,\'draft\',0,0,?,NOW())',[$scope,$month,$scope==='store'?$assignmentId:null,$scope==='backoffice'?$boUserId:null,$systemKey,$systemName,$uid]);
 $id=(int)bo_db()->lastInsertId();foreach(bo_kpi_master_rows($scope,true) as $m)bo_exec('INSERT INTO bo_kpi_assessment_items(assessment_id,master_id,kpi_name_snapshot,category_snapshot,weight_snapshot,max_score_snapshot,score,weighted_score,notes) VALUES(?,?,?,?,?,?,0,0,\'\')',[$id,(int)$m['id'],$m['kpi_name'],$m['category_name'],$m['weight'],$m['max_score']]);return $id;
}
function bo_kpi_recalc(int $assessmentId): array {$rows=bo_exec('SELECT * FROM bo_kpi_assessment_items WHERE assessment_id=?',[$assessmentId])->fetchAll()?:[];$sum=0.0;$w=0.0;foreach($rows as $r){$max=max(.01,(float)$r['max_score_snapshot']);$weight=(float)$r['weight_snapshot'];$score=max(0,min($max,(float)$r['score']));$weighted=($score/$max)*$weight;bo_exec('UPDATE bo_kpi_assessment_items SET score=?,weighted_score=? WHERE id=?',[$score,$weighted,(int)$r['id']]);$sum+=$weighted;$w+=$weight;}bo_exec('UPDATE bo_kpi_assessments SET final_score=?,total_weight=?,updated_at=NOW() WHERE id=?',[$sum,$w,$assessmentId]);return ['score'=>$sum,'weight'=>$w];}

$schemaReady=bo_kpi_table_exists('bo_kpi_masters')&&bo_kpi_table_exists('bo_kpi_assessments')&&bo_kpi_table_exists('bo_kpi_assessment_items');
$notice=(string)($_GET['notice']??'');$noticeType=(string)($_GET['notice_type']??'ok');
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  if(!$canWrite)throw new RuntimeException('Akses tulis hanya untuk Owner/Admin.');if(!$schemaReady)throw new RuntimeException('SQL KPI Back Office belum diimpor.');bo_kpi_check_csrf();$action=(string)($_POST['action']??'');$scope=(string)($_POST['scope']??'store');if(!in_array($scope,['store','backoffice'],true))throw new RuntimeException('Scope KPI tidak valid.');
  if($action==='save_master'){$id=(int)($_POST['id']??0);$name=trim((string)($_POST['kpi_name']??''));$cat=trim((string)($_POST['category_name']??''));$desc=trim((string)($_POST['description']??''));$weight=(float)str_replace(',','.',(string)($_POST['weight']??0));$max=(float)str_replace(',','.',(string)($_POST['max_score']??100));$sort=(int)($_POST['sort_order']??0);if($name===''||$weight<0||$weight>100||$max<=0)throw new RuntimeException('Nama, bobot 0–100, dan nilai maksimum wajib valid.');if($id>0)bo_exec('UPDATE bo_kpi_masters SET kpi_name=?,category_name=?,description=?,weight=?,max_score=?,sort_order=?,is_active=?,updated_at=NOW() WHERE id=? AND scope_key=?',[$name,$cat,$desc,$weight,$max,$sort,isset($_POST['is_active'])?1:0,$id,$scope]);else bo_exec('INSERT INTO bo_kpi_masters(scope_key,kpi_name,category_name,description,weight,max_score,sort_order,is_active,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,NOW())',[$scope,$name,$cat,$desc,$weight,$max,$sort,isset($_POST['is_active'])?1:0,$uid]);bo_kpi_redirect($scope==='store'?'store_master':'backoffice_master',$month,'Master KPI disimpan.');}
  if($action==='toggle_master'){$id=(int)($_POST['id']??0);bo_exec('UPDATE bo_kpi_masters SET is_active=IF(is_active=1,0,1),updated_at=NOW() WHERE id=? AND scope_key=?',[$id,$scope]);bo_kpi_redirect($scope==='store'?'store_master':'backoffice_master',$month,'Status KPI diperbarui.');}
  if($action==='save_assessment'){$assessmentId=(int)($_POST['assessment_id']??0);$assignmentId=(int)($_POST['assignment_id']??0);$boUserId=(int)($_POST['bo_user_id']??0);if($assessmentId<=0)$assessmentId=bo_kpi_build_assessment($scope,$month,$assignmentId,$boUserId,$uid);$a=bo_exec('SELECT status FROM bo_kpi_assessments WHERE id=? LIMIT 1',[$assessmentId])->fetch();if(!$a)throw new RuntimeException('Assessment tidak ditemukan.');if(($a['status']??'')==='final')throw new RuntimeException('KPI sudah Final dan terkunci.');foreach((array)($_POST['score']??[]) as $itemId=>$score){$notes=(string)(($_POST['notes']??[])[$itemId]??'');bo_exec('UPDATE bo_kpi_assessment_items SET score=?,notes=? WHERE id=? AND assessment_id=?',[(float)str_replace(',','.',(string)$score),trim($notes),(int)$itemId,$assessmentId]);}bo_exec('UPDATE bo_kpi_assessments SET general_notes=?,updated_by=?,updated_at=NOW() WHERE id=?',[trim((string)($_POST['general_notes']??'')),$uid,$assessmentId]);bo_kpi_recalc($assessmentId);bo_kpi_redirect($scope==='store'?'store_input':'backoffice_input',$month,'Draft KPI disimpan.');}
  if($action==='finalize_assessment'){$assessmentId=(int)($_POST['assessment_id']??0);$res=bo_kpi_recalc($assessmentId);if(abs($res['weight']-100)>0.01)throw new RuntimeException('Total bobot snapshot harus 100% sebelum KPI difinalkan.');bo_exec("UPDATE bo_kpi_assessments SET status='final',finalized_by=?,finalized_at=NOW(),updated_by=?,updated_at=NOW() WHERE id=? AND scope_key=?",[$uid,$uid,$assessmentId,$scope]);bo_kpi_redirect($scope==='store'?'store_input':'backoffice_input',$month,'KPI difinalkan dan dikunci.');}
 }catch(Throwable $e){bo_kpi_redirect($section,$month,$e->getMessage(),'err');}
}
$csrf=bo_kpi_csrf();
?>
<style>
.kpi-home{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}.kpi-card h3{margin:0 0 6px}.kpi-nav{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.kpi-score{width:90px}.kpi-note{min-width:220px}.kpi-master-form{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px;align-items:end}.kpi-master-form .wide{grid-column:span 2}.kpi-status{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.kpi-employee{margin-bottom:14px}.kpi-employee summary{cursor:pointer;font-weight:700}.kpi-meta{display:flex;gap:12px;flex-wrap:wrap;color:#64748b;font-size:13px}.kpi-metric{font-size:24px;font-weight:800}
</style>
<div class="page-title"><div><h1>KPI Pegawai</h1><div class="muted">KPI Toko dan Back Office dikelola lokal; KPI Dapur tetap sinkron dari website Dapur.</div></div></div>
<?php if($notice!==''): ?><div class="alert <?=($noticeType==='err'?'danger':'ok')?>"><?=e($notice)?></div><?php endif; ?>
<?php if(!$schemaReady): ?><div class="alert danger">Modul KPI baru belum aktif. Import <b>db/20260828_002_kpi_payroll_revision.sql</b> terlebih dahulu.</div><?php endif; ?>
<div class="kpi-nav"><a class="btn" href="?p=kpi&section=overview&month=<?=e($month)?>">Ringkasan</a><a class="btn" href="?p=kpi&section=store_input&month=<?=e($month)?>">KPI Toko</a><a class="btn" href="?p=kpi&section=dapur&month=<?=e($month)?>">KPI Dapur</a><a class="btn" href="?p=kpi&section=backoffice_input&month=<?=e($month)?>">KPI Back Office</a></div>

<?php if($section==='overview'): ?>
<div class="kpi-home">
 <div class="card kpi-card"><h3>KPI Toko</h3><p class="muted">Assessment disiplin, ketepatan waktu, SOP, pekerjaan tambahan, pelayanan, dan indikator lain dari master Back Office.</p><a class="btn primary" href="?p=kpi&section=store_input&month=<?=e($month)?>">Input KPI Toko</a> <a class="btn" href="?p=kpi&section=store_master&month=<?=e($month)?>">Master</a></div>
 <div class="card kpi-card"><h3>KPI Dapur</h3><p class="muted">Poin aktivitas tetap berasal dari website Dapur dan hanya dimonitor/sinkron di Back Office.</p><a class="btn primary" href="?p=kpi&section=dapur&month=<?=e($month)?>">Lihat KPI Dapur</a></div>
 <div class="card kpi-card"><h3>KPI Back Office</h3><p class="muted">Assessment khusus Admin Back Office untuk menjadi bobot insentif payroll Back Office.</p><a class="btn primary" href="?p=kpi&section=backoffice_input&month=<?=e($month)?>">Input KPI Back Office</a> <a class="btn" href="?p=kpi&section=backoffice_master&month=<?=e($month)?>">Master</a></div>
</div>

<?php elseif(in_array($section,['store_master','backoffice_master'],true)): $scope=bo_kpi_scope_from_section($section);$masters=$schemaReady?bo_kpi_master_rows($scope):[];$weightTotal=$schemaReady?bo_kpi_weight_total($scope):0; ?>
<div class="card"><div class="section-head"><div><h3>Master KPI <?=e($scope==='store'?'Toko':'Back Office')?></h3><div class="muted">Total bobot KPI aktif harus 100% agar assessment dapat difinalkan.</div></div><div class="kpi-metric"><?=e(number_format($weightTotal,2,',','.'))?>%</div></div>
<?php if($canWrite&&$schemaReady): ?><form method="post" class="kpi-master-form"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="save_master"><input type="hidden" name="scope" value="<?=e($scope)?>"><label>Nama KPI<input name="kpi_name" required placeholder="Contoh: Ketepatan waktu"></label><label>Kategori<input name="category_name" placeholder="Disiplin/Operasional"></label><label>Bobot (%)<input type="number" min="0" max="100" step="0.01" name="weight" required></label><label>Nilai Maksimum<input type="number" min="0.01" step="0.01" name="max_score" value="100" required></label><label>Urutan<input type="number" name="sort_order" value="0"></label><label><input style="width:auto" type="checkbox" name="is_active" checked> Aktif</label><label class="wide">Panduan/Deskripsi<input name="description" placeholder="Panduan penilaian"></label><button class="btn primary">Tambah KPI</button></form><?php endif; ?>
</div>
<div class="table-wrap section"><table><thead><tr><th>Nama</th><th>Kategori</th><th>Bobot</th><th>Maks</th><th>Panduan</th><th>Urutan</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($masters as $m): $mf='km-'.(int)$m['id']; ?><tr><td><form id="<?=e($mf)?>" method="post"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="save_master"><input type="hidden" name="scope" value="<?=e($scope)?>"><input type="hidden" name="id" value="<?=$m['id']?>"></form><input form="<?=e($mf)?>" name="kpi_name" value="<?=e($m['kpi_name'])?>" required></td><td><input form="<?=e($mf)?>" name="category_name" value="<?=e($m['category_name']??'')?>"></td><td><input form="<?=e($mf)?>" type="number" min="0" max="100" step="0.01" name="weight" value="<?=e($m['weight'])?>"></td><td><input form="<?=e($mf)?>" type="number" min="0.01" step="0.01" name="max_score" value="<?=e($m['max_score'])?>"></td><td><input form="<?=e($mf)?>" name="description" value="<?=e($m['description']??'')?>"></td><td><input form="<?=e($mf)?>" type="number" name="sort_order" value="<?=e($m['sort_order'])?>"></td><td><label><input form="<?=e($mf)?>" style="width:auto" type="checkbox" name="is_active" <?=!empty($m['is_active'])?'checked':''?>> Aktif</label></td><td><?php if($canWrite): ?><button form="<?=e($mf)?>" class="btn">Simpan</button><?php endif; ?></td></tr><?php endforeach;if(!$masters): ?><tr><td colspan="8">Master KPI belum dibuat.</td></tr><?php endif; ?></tbody></table></div>

<?php elseif(in_array($section,['store_input','backoffice_input'],true)): $scope=bo_kpi_scope_from_section($section);$emps=$scope==='store'?bo_kpi_store_employees():bo_kpi_admin_employees(); ?>
<div class="card"><div class="section-head"><div><h3>Input KPI <?=e($scope==='store'?'Toko':'Back Office')?></h3><div class="muted">KPI hanya menjadi dasar pembobotan insentif payroll.</div></div><form class="filters"><input type="hidden" name="p" value="kpi"><input type="hidden" name="section" value="<?=e($section)?>"><label>Bulan<input type="month" name="month" value="<?=e($month)?>"></label><button class="btn primary">Tampilkan</button></form></div></div>
<?php foreach($emps as $emp): $assignmentId=(int)($emp['assignment_id']??0);$boUserId=(int)($emp['bo_user_id']??0);$a=$schemaReady?bo_kpi_find_assessment($scope,$month,$assignmentId,$boUserId):null;$items=$a?bo_exec('SELECT * FROM bo_kpi_assessment_items WHERE assessment_id=? ORDER BY id',[(int)$a['id']])->fetchAll():[];$locked=$a&&($a['status']==='final'); ?>
<details class="card kpi-employee" <?=isset($_GET['employee'])&&((string)$_GET['employee']===(string)($scope==='store'?$assignmentId:$boUserId))?'open':''?>><summary><?=e($scope==='store'?$emp['canonical_name']:$emp['name'])?> <span class="muted">— <?=e($scope==='store'?$emp['system_name']:'Back Office')?> · <?=e($emp['role_key']??'admin')?></span> <span class="badge <?=$locked?'ok':'warn'?>"><?=e(strtoupper((string)($a['status']??'belum dinilai')))?></span></summary>
<div class="section"><div class="kpi-meta"><span>Nilai akhir: <b><?=e(number_format((float)($a['final_score']??0),2,',','.'))?></b></span><span>Total bobot snapshot: <?=e(number_format((float)($a['total_weight']??0),2,',','.'))?>%</span></div>
<?php if(!$a&&$schemaReady): ?><form method="post"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="save_assessment"><input type="hidden" name="scope" value="<?=e($scope)?>"><input type="hidden" name="assignment_id" value="<?=$assignmentId?>"><input type="hidden" name="bo_user_id" value="<?=$boUserId?>"><button class="btn primary">Mulai Penilaian</button></form>
<?php elseif($a): ?><form method="post"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="save_assessment"><input type="hidden" name="scope" value="<?=e($scope)?>"><input type="hidden" name="assessment_id" value="<?=$a['id']?>"><div class="table-wrap"><table><thead><tr><th>KPI</th><th>Bobot</th><th>Nilai/Maks</th><th>Nilai</th><th>Catatan</th></tr></thead><tbody><?php foreach($items as $it): ?><tr><td><b><?=e($it['kpi_name_snapshot'])?></b><br><small><?=e($it['category_snapshot']??'')?></small></td><td><?=e(number_format((float)$it['weight_snapshot'],2,',','.'))?>%</td><td><?=e(number_format((float)$it['score'],2,',','.'))?> / <?=e(number_format((float)$it['max_score_snapshot'],2,',','.'))?></td><td><input class="kpi-score" type="number" min="0" max="<?=e($it['max_score_snapshot'])?>" step="0.01" name="score[<?=$it['id']?>]" value="<?=e($it['score'])?>" <?=$locked?'disabled':''?>></td><td><input class="kpi-note" name="notes[<?=$it['id']?>]" value="<?=e($it['notes']??'')?>" <?=$locked?'disabled':''?>></td></tr><?php endforeach; ?></tbody></table></div><label>Catatan umum<textarea name="general_notes" <?=$locked?'disabled':''?>><?=e($a['general_notes']??'')?></textarea></label><?php if(!$locked&&$canWrite): ?><button class="btn">Simpan Draft</button><?php endif; ?></form><?php if(!$locked&&$canWrite): ?><form method="post" style="margin-top:8px"><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="finalize_assessment"><input type="hidden" name="scope" value="<?=e($scope)?>"><input type="hidden" name="assessment_id" value="<?=$a['id']?>"><button class="btn primary" data-confirm="Finalisasi akan mengunci KPI periode ini. Lanjutkan?">Final & Kunci</button></form><?php endif; ?><?php endif; ?></div></details>
<?php endforeach;if(!$emps): ?><div class="alert">Belum ada pegawai pada kelompok ini.</div><?php endif; ?>

<?php elseif(in_array($section,['store_recap','backoffice_recap'],true)): $scope=bo_kpi_scope_from_section($section);$rows=$schemaReady?bo_exec("SELECT a.*,COALESCE(p.canonical_name,u.name,'-') employee_name FROM bo_kpi_assessments a LEFT JOIN bo_employee_assignments ea ON ea.id=a.assignment_id LEFT JOIN bo_employee_people p ON p.id=ea.person_id LEFT JOIN bo_users u ON u.id=a.bo_user_id WHERE a.scope_key=? AND a.assessment_month=? ORDER BY a.system_name,employee_name",[$scope,$month])->fetchAll():[]; ?>
<div class="card"><h3>Rekap KPI <?=e($scope==='store'?'Toko':'Back Office')?> — <?=e($month)?></h3><div class="table-wrap"><table><thead><tr><th>Pegawai</th><th>Unit</th><th>Status</th><th>Bobot</th><th>Nilai Akhir</th><th>Finalisasi</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?=e($r['employee_name'])?></td><td><?=e($r['system_name'])?></td><td><span class="badge <?=($r['status']==='final')?'ok':'warn'?>"><?=e(strtoupper($r['status']))?></span></td><td><?=e(number_format((float)$r['total_weight'],2,',','.'))?>%</td><td><b><?=e(number_format((float)$r['final_score'],2,',','.'))?></b></td><td><?=e($r['finalized_at']??'-')?></td></tr><?php endforeach;if(!$rows): ?><tr><td colspan="6">Belum ada data.</td></tr><?php endif; ?></tbody></table></div></div>

<?php elseif($section==='dapur'): 
$rows=[];$errors=[];$totalPoints=0.0;$activityCount=0;$conns=bo_connections_by_type('dapur');foreach($conns as $conn){$res=bo_api_request_connection($conn,'api/backoffice/kpi_dapur.php',['month'=>$month]);if(empty($res['ok'])){$errors[]=(string)($conn['system_name']??'Dapur').': '.($res['message']??'API gagal');continue;}$payload=bo_ops_payload($res);foreach((array)($payload['employees']??[]) as $r){if(!is_array($r))continue;$r['_connection_name']=$conn['system_name']??'Dapur';$r['_system_key']=$conn['system_key']??'';$rows[]=$r;$totalPoints+=(float)($r['total_points']??0);$activityCount+=(int)($r['activity_count']??0);}}
?>
<div class="card"><div class="section-head"><div><h3>KPI Dapur — Sinkron Website Dapur</h3><div class="muted">Data tidak diedit di Back Office. Sumber tetap endpoint KPI dari masing-masing website Dapur.</div></div><form class="filters"><input type="hidden" name="p" value="kpi"><input type="hidden" name="section" value="dapur"><label>Bulan<input type="month" name="month" value="<?=e($month)?>"></label><button class="btn primary">Sinkron/Tampilkan</button></form></div></div>
<div class="grid section"><div class="card metric"><div class="label">Pegawai</div><div class="value"><?=count($rows)?></div></div><div class="card metric"><div class="label">Total Poin</div><div class="value"><?=e(number_format($totalPoints,2,',','.'))?></div></div><div class="card metric"><div class="label">Aktivitas</div><div class="value"><?=e($activityCount)?></div></div></div>
<?php foreach($errors as $er): ?><div class="alert danger"><?=e($er)?></div><?php endforeach; ?><div class="table-wrap section"><table><thead><tr><th>Nama</th><th>Dapur</th><th>Status</th><th>Aktivitas</th><th>Total Poin</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><b><?=e($r['name']??'-')?></b><br><small>ID: <?=e($r['employee_id']??'-')?></small></td><td><?=e($r['_connection_name'])?></td><td><span class="badge <?=($r['is_active']??true)?'ok':'danger'?>"><?=($r['is_active']??true)?'Aktif':'Nonaktif'?></span></td><td><?=e($r['activity_count']??0)?></td><td><b><?=e(number_format((float)($r['total_points']??0),2,',','.'))?></b></td></tr><?php endforeach;if(!$rows): ?><tr><td colspan="5">Data KPI Dapur belum tersedia.</td></tr><?php endif; ?></tbody></table></div>
<?php endif; ?>
