<?php
require_once __DIR__.'/../core/OperationalSummary.php';
$month=$_GET['month']??date('Y-m');if(!preg_match('/^\d{4}-\d{2}$/',$month))$month=date('Y-m');
$stores=bo_ops_fetch_summaries('adena',$month);$kitchens=bo_ops_fetch_summaries('dapur',$month);
$rows=[];$errors=[];
foreach($stores as $u){if(!$u['ok']){$errors[]=$u['name'].': '.$u['message'];continue;}$d=$u['data'];$rows[]=['unit'=>$u['name'],'type'=>'Toko','batches_today'=>bo_ops_num(bo_ops_first($d,[['production','batches_today'],'productions_today'],0)),'qty_today'=>bo_ops_num(bo_ops_first($d,[['production','qty_today'],'production_qty_today'],0)),'batches_month'=>bo_ops_num(bo_ops_first($d,[['production','batches_month'],'production_batches_month'],0)),'qty_month'=>bo_ops_num(bo_ops_first($d,[['production','qty_month'],'production_qty_month'],0)),'products'=>bo_ops_num(bo_ops_first($d,['active_products','products'],0))];}
foreach($kitchens as $u){if(!$u['ok']){$errors[]=$u['name'].': '.$u['message'];continue;}$d=$u['data'];$rows[]=['unit'=>$u['name'],'type'=>'Dapur','batches_today'=>bo_ops_num(bo_ops_first($d,['productions_today',['production','batches_today']],0)),'qty_today'=>bo_ops_num(bo_ops_first($d,['production_qty_today',['production','qty_today']],0)),'batches_month'=>bo_ops_num(bo_ops_first($d,['production_batches_month',['production','batches_month']],0)),'qty_month'=>bo_ops_num(bo_ops_first($d,['production_qty_month',['production','qty_month']],0)),'products'=>bo_ops_num(bo_ops_first($d,['active_finished_products','finished_products'],0))];}
$totalBatches=array_sum(array_column($rows,'batches_today'));$totalQty=array_sum(array_column($rows,'qty_today'));
?>
<div class="page-title"><div><h1>Produksi</h1><div class="muted">Produksi toko dan dapur dibedakan antara jumlah batch dan total kuantitas.</div></div></div>
<form class="filters"><input type="hidden" name="p" value="production"><div><label>Periode</label><input type="month" name="month" value="<?=e($month)?>"></div><div><button class="btn primary">Filter</button></div></form>
<div class="grid"><div class="card metric"><div class="label">Total Batch Hari Ini</div><div class="value"><?=e((int)$totalBatches)?></div><div class="sub">Semua unit</div></div><div class="card metric"><div class="label">Total Qty Hari Ini</div><div class="value"><?=e(number_format($totalQty,2,',','.'))?></div><div class="sub">Semua hasil produksi</div></div><div class="card metric"><div class="label">Unit Terbaca</div><div class="value"><?=e(count($rows))?></div><div class="sub">Toko + Dapur</div></div></div>
<div class="table-wrap section"><table><thead><tr><th>Unit</th><th>Jenis</th><th>Batch Hari Ini</th><th>Qty Hari Ini</th><th>Batch Bulan Ini</th><th>Qty Bulan Ini</th><th>Produk Aktif</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><b><?=e($r['unit'])?></b></td><td><?=e($r['type'])?></td><td><?=e((int)$r['batches_today'])?></td><td><?=e(number_format($r['qty_today'],2,',','.'))?></td><td><?=e((int)$r['batches_month'])?></td><td><?=e(number_format($r['qty_month'],2,',','.'))?></td><td><?=e((int)$r['products'])?></td></tr><?php endforeach;if(!$rows): ?><tr><td colspan="7">Belum ada data produksi yang dapat dibaca.</td></tr><?php endif; ?></tbody></table></div>
<?php if($errors): ?><div class="card section"><h3>Catatan API</h3><?php foreach($errors as $err): ?><div class="alert danger"><?=e($err)?></div><?php endforeach; ?></div><?php endif; ?>
