<?php
require_once __DIR__.'/../core/OperationalSummary.php';
$start=$_GET['start_date']??date('Y-m-01');$end=$_GET['end_date']??date('Y-m-d');$source=$_GET['source']??'all';if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$start))$start=date('Y-m-01');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$end))$end=date('Y-m-d');if($end<$start){$t=$start;$start=$end;$end=$t;}
$rows=[];$errors=[];
foreach([['type'=>'adena','label'=>'Toko'],['type'=>'dapur','label'=>'Dapur']] as $group){if($source!=='all'&&$source!==$group['type'])continue;foreach(bo_connections_by_type($group['type']) as $conn){$res=bo_api_request_connection($conn,'api/backoffice/sales_list.php',['start_date'=>$start,'end_date'=>$end]);if(empty($res['ok'])){$errors[]=(string)($conn['system_name']??$conn['system_key']).': '.($res['message']??'gagal');continue;}$d=bo_ops_payload($res);foreach((array)($d['rows']??[]) as $r){$r['_unit']=bo_ops_unit_name($conn,$d);$r['_type']=$group['type'];$rows[]=$r;}}}
usort($rows,fn($a,$b)=>strcmp((string)($b['date']??''),(string)($a['date']??'')));
$total=array_sum(array_map(fn($r)=>(float)($r['total']??0),$rows));
?>
<style>.sales-modal{position:fixed;inset:0;background:rgba(15,23,42,.55);display:none;align-items:center;justify-content:center;z-index:1000;padding:20px}.sales-modal.open{display:flex}.sales-modal-box{background:#fff;border-radius:14px;max-width:760px;width:100%;max-height:85vh;overflow:auto;padding:20px}.sales-detail-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px 18px}.sales-detail-grid div{padding:7px 0;border-bottom:1px solid #eef2f7}.sales-items{margin-top:14px}@media(max-width:650px){.sales-detail-grid{grid-template-columns:1fr}}</style>
<div class="page-title"><div><h1>Lihat Penjualan</h1><div class="muted">Gabungan transaksi toko dan dapur. Omset toko menggunakan nilai bersih setelah diskon dan revisi aktif.</div></div></div>
<form class="filters card" method="get"><input type="hidden" name="p" value="sales"><div><label>Dari</label><input type="date" name="start_date" value="<?=e($start)?>"></div><div><label>Sampai</label><input type="date" name="end_date" value="<?=e($end)?>"></div><div><label>Sumber</label><select name="source"><option value="all" <?=$source==='all'?'selected':''?>>Semua</option><option value="adena" <?=$source==='adena'?'selected':''?>>Toko</option><option value="dapur" <?=$source==='dapur'?'selected':''?>>Dapur</option></select></div><div><button class="btn primary">Tampilkan</button></div></form>
<div class="grid section"><div class="card metric"><div class="label">Jumlah Transaksi</div><div class="value"><?=number_format(count($rows),0,',','.')?></div></div><div class="card metric"><div class="label">Total Penjualan</div><div class="value"><?=money_id($total)?></div></div></div>
<div class="table-wrap section"><table><thead><tr><th>Tanggal</th><th>Sumber</th><th>No Transaksi</th><th>Tujuan/Customer</th><th>Jenis</th><th>Total</th><th></th></tr></thead><tbody><?php foreach($rows as $i=>$r): $payload=htmlspecialchars(json_encode($r,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),ENT_QUOTES,'UTF-8'); ?><tr><td><?=e($r['date']??'-')?></td><td><?=e($r['_unit'])?></td><td><?=e($r['transaction_no']??'-')?></td><td><?=e($r['destination']??$r['customer']??'-')?></td><td><?=e($r['sale_type']??($r['_type']==='adena'?'Penjualan toko':'Penjualan dapur'))?></td><td><?=money_id($r['total']??0)?></td><td><button type="button" class="btn js-sale-detail" data-row="<?=$payload?>">Detail</button></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="7">Belum ada penjualan pada periode ini.</td></tr><?php endif;?></tbody></table></div>
<?php foreach($errors as $err):?><div class="alert danger section"><?=e($err)?></div><?php endforeach;?>
<div class="sales-modal" id="salesModal"><div class="sales-modal-box"><div class="section-head"><h3>Detail Penjualan</h3><button type="button" class="btn" id="salesClose">Tutup</button></div><div id="salesDetail"></div></div></div>
<script>(function(){const m=document.getElementById('salesModal'),d=document.getElementById('salesDetail');function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}document.querySelectorAll('.js-sale-detail').forEach(b=>b.addEventListener('click',()=>{const r=JSON.parse(b.dataset.row);let items=(r.items||[]).map(x=>`<tr><td>${esc(x.product_name||x.item_name||'-')}</td><td>${esc(x.qty||0)}</td><td>${esc(x.net||x.line_total||0)}</td></tr>`).join('');d.innerHTML=`<div class="sales-detail-grid"><div><b>Sumber</b><br>${esc(r._unit)}</div><div><b>No transaksi</b><br>${esc(r.transaction_no)}</div><div><b>Tanggal</b><br>${esc(r.date)}</div><div><b>Customer/Tujuan</b><br>${esc(r.destination||r.customer||'-')}</div><div><b>Guide</b><br>${esc(r.guide||'-')}</div><div><b>Pembayaran</b><br>${esc(r.payment_method||'-')}</div><div><b>Diskon</b><br>${esc(r.discount||0)}</div><div><b>Total</b><br>${esc(r.total||0)}</div></div><div class="sales-items"><table><thead><tr><th>Item</th><th>Qty</th><th>Net</th></tr></thead><tbody>${items||'<tr><td colspan="3">Tidak ada detail item.</td></tr>'}</tbody></table></div>`;m.classList.add('open');}));document.getElementById('salesClose').onclick=()=>m.classList.remove('open');m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')});})();</script>
