<?php
$u=bo_user(); if(($u['role_key']??'')!=='owner'){ echo '<div class="page-title"><div><h1>Pengaturan</h1></div></div><div class="card"><div class="alert danger">Setting Backup Google Drive hanya dapat diakses owner.</div></div>'; return; }
$backupRoot=dirname(__DIR__);require_once $backupRoot.'/core/backup_safe.php';require_once $backupRoot.'/core/Company.php';backup_safe_register($backupRoot,'BACKOFFICE backup settings','html');
$svc=null;$loadError='';$msg=(string)($_SESSION['bo_backup_flash']??'');$err=(string)($_SESSION['bo_backup_flash_error']??'');unset($_SESSION['bo_backup_flash'],$_SESSION['bo_backup_flash_error']);
if(session_status()!==PHP_SESSION_ACTIVE)bo_session_start();if(empty($_SESSION['bo_backup_csrf']))$_SESSION['bo_backup_csrf']=bin2hex(random_bytes(24));$csrf=(string)$_SESSION['bo_backup_csrf'];
try{require_once $backupRoot.'/core/BackupAdapter.php';require_once __DIR__.'/backup_ui.php';$svc=bo_backup_service();}
catch(Throwable $e){$loadError=backup_safe_capture($backupRoot,'BACKOFFICE service bootstrap',$e);}
$relativeCallback=bo_url('backup_google_callback.php');$scheme=((!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')||strtolower((string)($_SERVER['HTTP_X_FORWARDED_PROTO']??''))==='https')?'https':'http';$callback=preg_match('~^https?://~i',$relativeCallback)?$relativeCallback:$scheme.'://'.($_SERVER['HTTP_HOST']??'localhost').'/'.ltrim($relativeCallback,'/');
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['company_branding_action'])){
 try{if(!hash_equals($csrf,(string)($_POST['backup_csrf']??'')))throw new RuntimeException('CSRF token tidak valid.');$companyName=trim((string)($_POST['company_name']??''));if($companyName==='')$companyName='Adena Group';bo_company_set('company_name',$companyName);if(isset($_FILES['company_logo'])&&is_array($_FILES['company_logo'])&&($_FILES['company_logo']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){if(($_FILES['company_logo']['error']??UPLOAD_ERR_OK)!==UPLOAD_ERR_OK)throw new RuntimeException('Upload logo gagal.');$tmp=(string)$_FILES['company_logo']['tmp_name'];$mime=(string)(mime_content_type($tmp)?:'');$ext=match($mime){'image/png'=>'png','image/jpeg'=>'jpg','image/webp'=>'webp',default=>''};if($ext==='')throw new RuntimeException('Logo harus PNG, JPG, atau WEBP.');if((int)($_FILES['company_logo']['size']??0)>2*1024*1024)throw new RuntimeException('Ukuran logo maksimal 2 MB.');$dir=$backupRoot.'/storage/branding';if(!is_dir($dir)&&!mkdir($dir,0755,true)&&!is_dir($dir))throw new RuntimeException('Folder branding tidak dapat dibuat.');foreach(glob($dir.'/company-logo.*')?:[] as $old)@unlink($old);$dest=$dir.'/company-logo.'.$ext;if(!move_uploaded_file($tmp,$dest))throw new RuntimeException('Logo gagal disimpan.');bo_company_set('company_logo','storage/branding/company-logo.'.$ext);}$_SESSION['bo_backup_flash']='Branding perusahaan berhasil disimpan.';header('Location: ?p=settings');exit;}catch(Throwable $e){$err=$e->getMessage();}
}
if($_SERVER['REQUEST_METHOD']==='POST'&&$svc&&!isset($_POST['company_branding_action'])){
 try{if(!hash_equals($csrf,(string)($_POST['backup_csrf']??'')))throw new RuntimeException('CSRF token tidak valid.');$a=(string)($_POST['backup_action']??'');
  if($a==='repair'){$svc->repairInfrastructure();$msg='Struktur backup berhasil diperiksa dan diperbaiki.';}
  elseif($a==='save_config'){$svc->saveConfiguration($_POST);$msg='Konfigurasi backup berhasil disimpan.';}
  elseif($a==='connect'){$state=bin2hex(random_bytes(24));$_SESSION['backup_oauth_state']=$state;header('Location: '.$svc->authorizationUrl($callback,$state));backup_safe_finish();exit;}
  elseif($a==='test'){$r=$svc->testConnection();$msg='Koneksi berhasil ke '.($r['email']??'Google Drive').'.';}
  elseif($a==='disconnect'){$svc->disconnect();$msg='Koneksi Google Drive diputus.';}
  elseif($a==='download_key'){$site=preg_replace('/[^A-Za-z0-9_-]+/','-',(string)$svc->get('site_code',$svc->appKey()));while(ob_get_level()>0)@ob_end_clean();header('Content-Type: text/plain; charset=utf-8');header('Content-Disposition: attachment; filename="backup-recovery-key-'.$site.'.txt"');echo $svc->recoveryKeyText();backup_safe_finish();exit;}
  elseif($a==='run'){$r=$svc->runBackup((string)($_POST['backup_type']??'daily'),'owner');$msg='Backup berhasil: '.$r['filename'];}
  elseif($a==='test_restore'){$jobId=(int)($_POST['backup_job_id']??0);if($jobId<=0){$type=(string)($_POST['backup_type']??'daily');$latest=$svc->successfulBackups($type,1);if(!$latest)throw new RuntimeException('Belum ada backup berhasil untuk timeframe yang dipilih. Jalankan Backup Sekarang terlebih dahulu.');$jobId=(int)$latest[0]['id'];}$r=$svc->testRestore($jobId);$msg='Tes Restore lulus: database valid, file aplikasi '.(int)($r['application_files']??0).', private uploads '.(int)($r['private_uploads']??0).'.';}
  elseif($a==='restore'){$r=$svc->restoreBackup((int)($_POST['backup_job_id']??0),(string)($_POST['restore_confirm']??''));$msg='Restore berhasil. Pre-restore backup: '.($r['pre_restore']??'-');}
 }catch(Throwable $e){$err=backup_safe_capture($backupRoot,'BACKOFFICE backup action',$e);}
}
?><div class="page-title"><div><h1>Pengaturan</h1><div class="muted">Branding perusahaan dan backup Back Office.</div></div></div><div class="card"><h3>Branding Perusahaan</h3><div class="muted">Logo dan nama ini dipakai otomatis pada Slip Gaji A4.</div><form method="post" enctype="multipart/form-data"><input type="hidden" name="backup_csrf" value="<?=e($csrf)?>"><input type="hidden" name="company_branding_action" value="save"><div class="grid-2"><div><label>Nama perusahaan</label><input name="company_name" value="<?=e(bo_company_name())?>"></div><div><label>Logo perusahaan (PNG/JPG/WEBP, maks. 2 MB)</label><input type="file" name="company_logo" accept="image/png,image/jpeg,image/webp"><?php $brandLogo=bo_company_logo_data_uri(); if($brandLogo!==''): ?><div style="margin-top:8px"><img src="<?=e($brandLogo)?>" alt="Logo perusahaan" style="max-height:64px;max-width:180px;object-fit:contain"></div><?php endif; ?></div></div><div class="section"><button class="btn primary">Simpan Branding</button></div></form></div><div class="page-title section"><div><h1>Setting Backup Google Drive</h1><div class="muted">Backup otomatis terenkripsi untuk Back Office.</div></div></div><?php if($msg):?><div class="alert success"><?=e($msg)?></div><?php endif;?><?php if($err):?><div class="alert danger"><?=e($err)?></div><?php endif;?><?php
if($svc){$cronCommand=backup_build_cron_command($svc,dirname(__DIR__).'/cron_backup.php');$relativeCron=bo_url('cron_backup.php?key='.rawurlencode((string)$svc->get('cron_secret','')));$cronUrl=preg_match('~^https?://~i',$relativeCron)?$relativeCron:$scheme.'://'.($_SERVER['HTTP_HOST']??'localhost').'/'.ltrim($relativeCron,'/');$connectUrl=bo_url('backup_google_connect.php?token='.rawurlencode($csrf));backup_render_settings($svc,$callback,$cronCommand,$cronUrl,'<input type="hidden" name="backup_csrf" value="'.e($csrf).'">','?p=settings',$connectUrl);}
else{backup_safe_render_error($loadError,$backupRoot);}backup_safe_finish(); ?>
