<?php
require_once __DIR__.'/core/Auth.php';bo_require_login();
require_once __DIR__.'/core/ApiClient.php';
require_once __DIR__.'/core/Payroll.php';
require_once __DIR__.'/core/Company.php';
$month=(string)($_GET['month']??date('Y-m'));if(!bo_payroll_valid_month($month))$month=date('Y-m');
$assignmentId=(int)($_GET['assignment_id']??0);$boUserId=(int)($_GET['bo_user_id']??0);if($assignmentId<=0&&$boUserId<=0){http_response_code(400);exit('Pegawai tidak valid.');}
$run=bo_payroll_run($month);$locked=$run&&in_array((string)($run['status']??''),['final','paid'],true);$item=null;
if($locked){foreach((array)($run['items']??[]) as $it){if(($assignmentId>0&&(int)($it['assignment_id']??0)===$assignmentId)||($boUserId>0&&(int)($it['bo_user_id']??0)===$boUserId)){$item=$it;if(!empty($it['snapshot_json'])){$sj=json_decode((string)$it['snapshot_json'],true);if(is_array($sj))$item=array_merge($it,$sj);}break;}}}
else{$calc=bo_payroll_compute($month);foreach($calc['items'] as $it){if(($assignmentId>0&&(int)($it['assignment_id']??0)===$assignmentId)||($boUserId>0&&(int)($it['bo_user_id']??0)===$boUserId)){$item=$it;break;}}}
if(!$item){http_response_code(404);exit('Data payroll pegawai tidak ditemukan untuk periode ini.');}
$name=(string)($item['employee_name']??$item['employee_name_snapshot']??'-');$role=(string)($item['role_key']??$item['role_key_snapshot']??'-');$unit=(string)($item['unit_name']??$item['unit_name_snapshot']??'-');
$gross=(float)($item['incentive_gross']??$item['incentive_amount']??$item['incentive']??0);$leave=(float)($item['leave_deduction']??0);$late=(float)($item['late_early_deduction']??0);$redis=(float)($item['incentive_redistributed']??0);$finalIncentive=(float)($locked?($item['incentive_amount']??0):($item['incentive']??0));
$otherDed=(float)($item['bpjs_kesehatan']??0)+(float)($item['bpjs_ketenagakerjaan']??0)+(float)($item['pph21']??0)+(float)($item['punishment']??0)+(float)($item['kasbon']??0);$income=(float)($item['base_salary']??0)+(float)($item['overtime']??0)+(float)($item['admin_share']??0)+$finalIncentive;$thp=(float)($item['take_home']??max(0,$income-$otherDed));
$months=['01'=>'Januari','02'=>'Februari','03'=>'Maret','04'=>'April','05'=>'Mei','06'=>'Juni','07'=>'Juli','08'=>'Agustus','09'=>'September','10'=>'Oktober','11'=>'November','12'=>'Desember'];[$yy,$mm]=explode('-',$month);$period=($months[$mm]??$mm).' '.$yy;
$company=bo_company_name();$logoData='';$lp=bo_company_logo_path();if($lp){$mime=(string)(mime_content_type($lp)?:'image/png');$logoData='data:'.$mime.';base64,'.base64_encode((string)file_get_contents($lp));}
function slip_money($v){return 'Rp '.number_format((float)$v,0,',','.');}
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Slip Gaji - <?=e($name)?> - <?=e($period)?></title><style>
@page{size:A4 portrait;margin:12mm}*{box-sizing:border-box}body{margin:0;background:#eef2f7;font-family:Arial,Helvetica,sans-serif;color:#172033;font-size:11px}.toolbar{max-width:210mm;margin:12px auto;display:flex;gap:8px;justify-content:flex-end}.btn{border:1px solid #d7dce4;background:white;padding:9px 13px;border-radius:8px;cursor:pointer;font-weight:700}.btn.primary{background:#1769e0;color:white;border-color:#1769e0}.sheet{width:210mm;min-height:297mm;margin:0 auto 24px;background:white;padding:12mm;box-shadow:0 10px 35px rgba(15,23,42,.14)}.header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #172033;padding-bottom:10px}.brand{display:flex;gap:10px;align-items:center}.logo{width:48px;height:48px;object-fit:contain}.fallback{width:48px;height:48px;border-radius:10px;background:#1769e0;color:#fff;display:flex;align-items:center;justify-content:center;font-size:22px;font-weight:800}.company{font-size:18px;font-weight:800}.muted{color:#667085}.title{text-align:right}.title h1{margin:0;font-size:20px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:6px 28px;margin:14px 0}.meta div{display:grid;grid-template-columns:90px 8px 1fr}.cols{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px}.box{border:1px solid #d9dee8;border-radius:8px;overflow:hidden}.box h3{margin:0;padding:8px 10px;background:#f3f6fb;font-size:11px;text-transform:uppercase;letter-spacing:.03em}.box table{width:100%;border-collapse:collapse}.box td{padding:7px 9px;border-top:1px solid #e7eaf0}.box td:last-child{text-align:right;font-weight:600;white-space:nowrap}.total td{font-weight:800;background:#fafbfd}.thp{margin:14px 0;border:1px solid #9fc4ff;background:#eef6ff;border-radius:8px;padding:12px;display:flex;justify-content:space-between;align-items:center;font-size:17px;font-weight:800;color:#0d3978}.detail{margin-top:12px}.detail table{width:100%;border-collapse:collapse;border:1px solid #d9dee8}.detail th,.detail td{padding:7px 8px;border:1px solid #d9dee8;text-align:left}.detail th{background:#f3f6fb}.detail td:last-child{text-align:right}.foot{display:grid;grid-template-columns:1.3fr .7fr;gap:20px;margin-top:20px}.sign{text-align:center}.sign-space{height:48px}.small{font-size:9.5px}.status{margin-top:8px;font-size:9px;color:#667085}@media print{body{background:white}.toolbar{display:none}.sheet{width:auto;min-height:auto;margin:0;padding:0;box-shadow:none}.cols{break-inside:avoid}.detail{break-inside:avoid}.foot{break-inside:avoid}}
</style></head><body><div class="toolbar"><button class="btn" onclick="history.back()">Kembali</button><button class="btn primary" onclick="window.print()">Cetak / Simpan PDF</button></div><main class="sheet"><header class="header"><div class="brand"><?php if($logoData!==''): ?><img class="logo" src="<?=e($logoData)?>" alt="Logo"><?php else: ?><div class="fallback"><?=e(strtoupper(substr($company,0,1)))?></div><?php endif; ?><div><div class="company"><?=e($company)?></div><div class="muted">Slip penggajian pegawai</div></div></div><div class="title"><h1>SLIP GAJI</h1><div>Periode <?=e($period)?></div></div></header>
<section class="meta"><div><span>Nama</span><b>:</b><strong><?=e($name)?></strong></div><div><span>Status Payroll</span><b>:</b><span><?=e($locked?strtoupper((string)$run['status']):'DRAFT')?></span></div><div><span>Unit</span><b>:</b><span><?=e($unit)?></span></div><div><span>Jabatan/Role</span><b>:</b><span><?=e($role)?></span></div></section>
<section class="cols"><div class="box"><h3>A. Pendapatan</h3><table><tr><td>Gaji Pokok</td><td><?=slip_money($item['base_salary']??0)?></td></tr><tr><td>Lembur</td><td><?=slip_money($item['overtime']??0)?></td></tr><?php if((float)($item['admin_share']??0)>0): ?><tr><td>Bagian Admin</td><td><?=slip_money($item['admin_share'])?></td></tr><?php endif; ?><tr><td>Insentif Final</td><td><?=slip_money($finalIncentive)?></td></tr><tr class="total"><td>Total Pendapatan</td><td><?=slip_money($income)?></td></tr></table></div><div class="box"><h3>B. Potongan Non-Insentif</h3><table><tr><td>BPJS Kesehatan</td><td><?=slip_money($item['bpjs_kesehatan']??0)?></td></tr><tr><td>BPJS Ketenagakerjaan</td><td><?=slip_money($item['bpjs_ketenagakerjaan']??0)?></td></tr><tr><td>PPh 21</td><td><?=slip_money($item['pph21']??0)?></td></tr><tr><td>Punishment</td><td><?=slip_money($item['punishment']??0)?></td></tr><tr><td>Kasbon</td><td><?=slip_money($item['kasbon']??0)?></td></tr><tr class="total"><td>Total Potongan</td><td><?=slip_money($otherDed)?></td></tr></table></div></section>
<div class="thp"><span>TAKE HOME PAY (THP)</span><span><?=slip_money($thp)?></span></div>
<section class="detail"><table><thead><tr><th colspan="3">Rincian Penyesuaian Insentif</th></tr><tr><th>Keterangan</th><th>Dasar</th><th>Nominal</th></tr></thead><tbody><tr><td>Insentif awal</td><td>Sebelum koreksi cuti/keterlambatan</td><td><?=slip_money($gross)?></td></tr><tr><td>Pengurangan karena cuti</td><td><?=e(number_format((float)($item['leave_days']??0),2,',','.'))?> hari / target <?=e(number_format((float)($item['leave_target_workdays']??0),2,',','.'))?> hari</td><td>- <?=slip_money($leave)?></td></tr><tr><td>Pengurangan terlambat / pulang cepat</td><td><?=e((string)($item['late_early_notes']??'-'))?></td><td>- <?=slip_money($late)?></td></tr><tr><td>Redistribusi insentif diterima</td><td>Redistribusi dari pool unit</td><td>+ <?=slip_money($redis)?></td></tr><tr class="total"><td colspan="2">Insentif Final</td><td><?=slip_money($finalIncentive)?></td></tr></tbody></table></section>
<section class="foot"><div><strong>Catatan</strong><div class="small muted">Slip gaji ini merupakan ringkasan payroll periode <?=e($period)?>. Pengurangan cuti serta terlambat/pulang cepat telah diperhitungkan pada insentif final dan tidak dipotong ulang dari gaji pokok.</div><div class="status">Dicetak <?=e(date('d-m-Y H:i'))?> WIB</div></div><div class="sign"><div>Hormat kami,</div><div class="sign-space"></div><strong><?=e($company)?></strong></div></section></main></body></html>
