<?php
require_once __DIR__.'/OperationalSummary.php';

function bo_payroll_schema_ready(): bool {
  return function_exists('bo_table_exists')
    && bo_table_exists('bo_payroll_unit_settings')
    && bo_table_exists('bo_payroll_employee_settings')
    && bo_table_exists('bo_payroll_runs')
    && bo_table_exists('bo_payroll_items')
    && bo_table_exists('bo_payroll_unit_period_settings')
    && bo_table_exists('bo_payroll_employee_period_settings')
    && bo_table_exists('bo_payroll_kpi_target_period_settings')
    && bo_table_exists('bo_kpi_assessments');
}
function bo_payroll_unit_key(string $type,string $systemKey): string {return strtolower(trim($type)).':'.trim($systemKey);}
function bo_payroll_money($v): float {return round(max(0,(float)$v),2);}
function bo_payroll_upsert_default_units(): void {
 if(!bo_payroll_schema_ready())return;$units=[];
 foreach(bo_connections_by_type('adena') as $c)$units[]=['store',(string)($c['system_key']??''),(string)($c['system_name']??$c['system_key']??'Toko')];
 foreach(bo_connections_by_type('dapur') as $c)$units[]=['dapur',(string)($c['system_key']??''),(string)($c['system_name']??$c['system_key']??'Dapur')];
 $units[]=['backoffice','backoffice','Back Office'];
 foreach($units as [$type,$key,$name]){if($key==='')continue;bo_exec("INSERT INTO bo_payroll_unit_settings(unit_type,system_key,unit_name,pool_percentage,is_active,created_at) VALUES(?,?,?,0,1,NOW()) ON DUPLICATE KEY UPDATE unit_name=VALUES(unit_name),updated_at=NOW()",[$type,$key,$name]);}
}
function bo_payroll_valid_month(string $month): bool { return (bool)preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$month); }
function bo_payroll_previous_period_month(string $table,string $month): ?string {
 if(!bo_payroll_valid_month($month))return null;
 $allowed=['bo_payroll_unit_period_settings','bo_payroll_employee_period_settings','bo_payroll_kpi_target_period_settings'];if(!in_array($table,$allowed,true))return null;
 $st=bo_exec("SELECT MAX(payroll_month) FROM {$table} WHERE payroll_month<?",[$month]);$v=$st->fetchColumn();return $v!==false&&$v!==null?(string)$v:null;
}
function bo_payroll_seed_period(string $month): void {
 if(!bo_payroll_schema_ready()||!bo_payroll_valid_month($month))return;
 bo_payroll_upsert_default_units();
 $cnt=(int)bo_exec('SELECT COUNT(*) FROM bo_payroll_unit_period_settings WHERE payroll_month=?',[$month])->fetchColumn();
 if($cnt===0){$prev=bo_payroll_previous_period_month('bo_payroll_unit_period_settings',$month);if($prev){bo_exec("INSERT INTO bo_payroll_unit_period_settings(payroll_month,unit_type,system_key,unit_name,pool_percentage,is_active,seeded_from_month,created_at) SELECT ?,unit_type,system_key,unit_name,pool_percentage,is_active,?,NOW() FROM bo_payroll_unit_period_settings WHERE payroll_month=?",[$month,$prev,$prev]);}else{bo_exec("INSERT INTO bo_payroll_unit_period_settings(payroll_month,unit_type,system_key,unit_name,pool_percentage,is_active,seeded_from_month,created_at) SELECT ?,unit_type,system_key,unit_name,pool_percentage,is_active,NULL,NOW() FROM bo_payroll_unit_settings",[$month]);}}
 $cnt=(int)bo_exec('SELECT COUNT(*) FROM bo_payroll_employee_period_settings WHERE payroll_month=?',[$month])->fetchColumn();
 if($cnt===0){$prev=bo_payroll_previous_period_month('bo_payroll_employee_period_settings',$month);if($prev){bo_exec("INSERT INTO bo_payroll_employee_period_settings(payroll_month,assignment_id,bo_user_id,base_salary,overtime,bpjs_kesehatan,bpjs_ketenagakerjaan,punishment,kasbon,is_eligible,notes,seeded_from_month,created_at) SELECT ?,assignment_id,bo_user_id,base_salary,overtime,bpjs_kesehatan,bpjs_ketenagakerjaan,0,0,is_eligible,notes,?,NOW() FROM bo_payroll_employee_period_settings WHERE payroll_month=?",[$month,$prev,$prev]);}else{bo_exec("INSERT INTO bo_payroll_employee_period_settings(payroll_month,assignment_id,bo_user_id,base_salary,overtime,bpjs_kesehatan,bpjs_ketenagakerjaan,punishment,kasbon,is_eligible,notes,seeded_from_month,created_at) SELECT ?,assignment_id,bo_user_id,base_salary,overtime,COALESCE(bpjs_kesehatan,0),COALESCE(bpjs_ketenagakerjaan,0),0,0,is_eligible,notes,NULL,NOW() FROM bo_payroll_employee_settings",[$month]);}}
 $cnt=(int)bo_exec('SELECT COUNT(*) FROM bo_payroll_kpi_target_period_settings WHERE payroll_month=?',[$month])->fetchColumn();
 if($cnt===0){$prev=bo_payroll_previous_period_month('bo_payroll_kpi_target_period_settings',$month);if($prev){bo_exec("INSERT INTO bo_payroll_kpi_target_period_settings(payroll_month,unit_type,system_key,role_key,target_value,seeded_from_month,created_at) SELECT ?,unit_type,system_key,role_key,target_value,?,NOW() FROM bo_payroll_kpi_target_period_settings WHERE payroll_month=?",[$month,$prev,$prev]);}else{bo_exec("INSERT INTO bo_payroll_kpi_target_period_settings(payroll_month,unit_type,system_key,role_key,target_value,seeded_from_month,created_at) SELECT ?,unit_type,system_key,role_key,target_value,NULL,NOW() FROM bo_payroll_kpi_targets",[$month]);}}
 // Unit baru yang belum pernah ada tetap ditambahkan untuk bulan terpilih.
 bo_exec("INSERT IGNORE INTO bo_payroll_unit_period_settings(payroll_month,unit_type,system_key,unit_name,pool_percentage,is_active,created_at) SELECT ?,unit_type,system_key,unit_name,pool_percentage,is_active,NOW() FROM bo_payroll_unit_settings",[$month]);
}
function bo_payroll_unit_settings(string $month): array {bo_payroll_seed_period($month);$rows=bo_exec("SELECT * FROM bo_payroll_unit_period_settings WHERE payroll_month=? ORDER BY FIELD(unit_type,'store','dapur','backoffice'),unit_name",[$month])->fetchAll()?:[];$out=[];foreach($rows as $r)$out[bo_payroll_unit_key((string)$r['unit_type'],(string)$r['system_key'])]=$r;return $out;}
function bo_payroll_employee_settings(string $month): array {bo_payroll_seed_period($month);$rows=bo_exec('SELECT * FROM bo_payroll_employee_period_settings WHERE payroll_month=?',[$month])->fetchAll()?:[];$out=[];foreach($rows as $r){if((int)($r['assignment_id']??0)>0)$out['assignment:'.(int)$r['assignment_id']]=$r;elseif((int)($r['bo_user_id']??0)>0)$out['admin:'.(int)$r['bo_user_id']]=$r;}return $out;}
function bo_payroll_assignment_rows(): array {return bo_exec("SELECT a.id assignment_id,a.person_id,a.source_system,a.system_key,a.system_name,a.external_employee_id,a.username,a.role_key,a.role_label,a.location,a.is_active assignment_active,p.canonical_name,p.email,p.phone,p.is_active person_active,p.manually_disabled FROM bo_employee_assignments a JOIN bo_employee_people p ON p.id=a.person_id WHERE a.is_active=1 AND p.is_active=1 AND p.manually_disabled=0 AND LOWER(TRIM(COALESCE(a.role_key,''))) NOT IN ('owner','superadmin') ORDER BY a.source_system,a.system_name,p.canonical_name")->fetchAll()?:[];}
function bo_payroll_admin_rows(): array {if(!bo_table_exists('bo_users'))return [];return bo_exec("SELECT id,name,username,email,role_key,is_active FROM bo_users WHERE is_active=1 AND LOWER(TRIM(role_key))='admin' ORDER BY name")->fetchAll()?:[];}

function bo_payroll_local_kpi_maps(string $month): array {
 $maps=['store'=>[],'backoffice'=>[],'errors'=>[]];
 $rows=bo_exec("SELECT id,scope_key,assignment_id,bo_user_id,final_score,status FROM bo_kpi_assessments WHERE assessment_month=?",[$month])->fetchAll()?:[];
 foreach($rows as $r){if(($r['status']??'')!=='final')continue;if($r['scope_key']==='store'&&(int)$r['assignment_id']>0)$maps['store'][(int)$r['assignment_id']]=$r;if($r['scope_key']==='backoffice'&&(int)$r['bo_user_id']>0)$maps['backoffice'][(int)$r['bo_user_id']]=$r;}
 return $maps;
}
function bo_payroll_dapur_kpi_map(string $month): array {
 $map=['rows'=>[],'errors'=>[]];
 foreach(bo_connections_by_type('dapur') as $conn){$key=(string)($conn['system_key']??'');$res=bo_api_request_connection($conn,'api/backoffice/kpi_dapur.php',['month'=>$month]);if(empty($res['ok'])){$map['errors'][]=(string)($conn['system_name']??$key).': '.($res['message']??'KPI Dapur gagal');continue;}$p=bo_ops_payload($res);foreach((array)($p['employees']??[]) as $r){if(!is_array($r))continue;$eid=(string)($r['employee_id']??'');if($eid!=='')$map['rows'][$key][$eid]=$r;}}
 return $map;
}
function bo_payroll_norm_label(string $v): string {
 $v=strtolower(trim($v));$v=preg_replace('/[^a-z0-9]+/',' ',$v);return trim((string)$v);
}
function bo_payroll_category_amount(array $data,string $wanted): array {
 $wanted=bo_payroll_norm_label($wanted);$directKeys=[$wanted,$wanted.'_revenue',$wanted.'_sales','sales_'.$wanted,'revenue_'.$wanted,'omset_'.$wanted];
 foreach($directKeys as $k){if(array_key_exists($k,$data)&&is_numeric($data[$k]))return ['found'=>true,'amount'=>bo_payroll_money($data[$k]),'source'=>$k];}
 $containers=['sales_by_category','revenue_by_category','category_sales','sales_categories','omset_by_category','revenue_categories','expenses'];
 foreach($containers as $ck){if(!isset($data[$ck])||!is_array($data[$ck]))continue;$box=$data[$ck];foreach($box as $key=>$row){
   if(is_numeric($row)&&bo_payroll_norm_label((string)$key)===$wanted)return ['found'=>true,'amount'=>bo_payroll_money($row),'source'=>$ck.'.'.$key];
   if(!is_array($row))continue;$label='';foreach(['category','category_name','name','label','type','group'] as $lk){if(isset($row[$lk])&&trim((string)$row[$lk])!==''){$label=(string)$row[$lk];break;}}
   if(bo_payroll_norm_label($label)!==$wanted)continue;foreach(['revenue','sales','amount','total','value','omset'] as $vk){if(isset($row[$vk])&&is_numeric($row[$vk]))return ['found'=>true,'amount'=>bo_payroll_money($row[$vk]),'source'=>$ck.'.'.$vk];}
  }}
 return ['found'=>false,'amount'=>0.0,'source'=>''];
}
function bo_payroll_store_revenue_basis(string $systemKey,string $systemName,array $data,float $gross): array {
 $identity=bo_payroll_norm_label($systemKey.' '.$systemName);$rules=[];if(str_contains($identity,'tjq'))$rules=['sepiak','jajanan','kemasan'];elseif(str_contains($identity,'pgk'))$rules=['kemasan'];
 $deductions=[];$missing=[];$total=0.0;foreach($rules as $cat){$m=bo_payroll_category_amount($data,$cat);if($m['found']){$deductions[$cat]=$m['amount'];$total+=$m['amount'];}else{$deductions[$cat]=0.0;$missing[]=$cat;}}
 return ['gross'=>$gross,'deduction_total'=>$total,'deductions'=>$deductions,'missing'=>$missing,'basis'=>max(0,round($gross-$total,2))];
}
function bo_payroll_financial_map(string $month): array {
 $out=['store'=>[],'dapur'=>[],'store_total'=>0.0,'store_gross_total'=>0.0,'dapur_external_total'=>0.0,'errors'=>[]];
 foreach(bo_ops_fetch_financials('adena',$month,true) as $u){$key=(string)($u['connection']['system_key']??'');if(!$u['ok']){$out['errors'][]=$u['name'].': '.$u['message'];continue;}$gross=bo_payroll_money($u['data']['sales_revenue']??0);$adj=bo_payroll_store_revenue_basis($key,(string)$u['name'],$u['data'],$gross);$rev=(float)$adj['basis'];if($adj['missing'])$out['errors'][]=$u['name'].': kategori pengurang omset payroll belum tersedia dari API: '.implode(', ',$adj['missing']).'. Basis omset belum dikurangi untuk kategori yang tidak ditemukan.';$out['store'][$key]=['name'=>$u['name'],'revenue'=>$rev,'gross_revenue'=>$gross,'revenue_adjustments'=>$adj,'data'=>$u['data']];$out['store_total']+=$rev;$out['store_gross_total']+=$gross;}
 foreach(bo_ops_fetch_financials('dapur',$month,false) as $u){$key=(string)($u['connection']['system_key']??'');if(!$u['ok']){$out['errors'][]=$u['name'].': '.$u['message'];continue;}$external=bo_payroll_money($u['data']['sales_revenue']??0);$internal=bo_payroll_money($u['data']['internal_distribution_value']??0);$basis=$external+$internal;$out['dapur'][$key]=['name'=>$u['name'],'revenue'=>$basis,'external_revenue'=>$external,'internal_distribution'=>$internal,'data'=>$u['data']];$out['dapur_external_total']+=$external;}
 $out['backoffice_revenue']=$out['store_gross_total']+$out['dapur_external_total'];return $out;
}
function bo_payroll_default_target(string $month,string $role): float {bo_payroll_seed_period($month);$role=strtolower(trim($role));$st=bo_exec("SELECT target_value FROM bo_payroll_kpi_target_period_settings WHERE payroll_month=? AND unit_type='dapur' AND system_key='*' AND role_key=? LIMIT 1",[$month,$role]);$v=$st->fetchColumn();return $v!==false?(float)$v:100.0;}
function bo_payroll_target(string $month,string $unitType,string $systemKey,string $role): float {if($unitType!=='dapur')return 100.0;bo_payroll_seed_period($month);$role=strtolower(trim($role));$st=bo_exec("SELECT target_value FROM bo_payroll_kpi_target_period_settings WHERE payroll_month=? AND unit_type='dapur' AND system_key=? AND role_key=? LIMIT 1",[$month,$systemKey,$role]);$v=$st->fetchColumn();if($v!==false)return max(.01,(float)$v);return max(.01,bo_payroll_default_target($month,$role));}

function bo_payroll_compute(string $month): array {
 bo_payroll_seed_period($month);$unitSettings=bo_payroll_unit_settings($month);$employeeSettings=bo_payroll_employee_settings($month);$financial=bo_payroll_financial_map($month);$localKpi=bo_payroll_local_kpi_maps($month);$dapurKpi=bo_payroll_dapur_kpi_map($month);$items=[];$groups=[];$kpiErrors=$dapurKpi['errors'];
 foreach(bo_payroll_assignment_rows() as $a){
  $unitType=((string)$a['source_system']==='dapur')?'dapur':'store';$systemKey=(string)$a['system_key'];$unitKey=bo_payroll_unit_key($unitType,$systemKey);$us=$unitSettings[$unitKey]??['pool_percentage'=>0,'is_active'=>1,'unit_name'=>$a['system_name']];if(empty($us['is_active']))continue;$es=$employeeSettings['assignment:'.(int)$a['assignment_id']]??[];if(isset($es['is_eligible'])&&(int)$es['is_eligible']!==1)continue;
  $rev=(float)($financial[$unitType][$systemKey]['revenue']??0);$pct=(float)($us['pool_percentage']??0);$budget=round($rev*$pct/100,2);$kpiRaw=0.0;$target=100.0;$score=0.0;$source='Belum Final';
  if($unitType==='store'){$kr=$localKpi['store'][(int)$a['assignment_id']]??null;if($kr){$kpiRaw=(float)$kr['final_score'];$score=max(0,min(120,$kpiRaw));$source='KPI Toko Back Office · Final';}}
  else{$kr=$dapurKpi['rows'][$systemKey][(string)$a['external_employee_id']]??null;$target=bo_payroll_target($month,'dapur',$systemKey,(string)$a['role_key']);if($kr){$kpiRaw=max(0,(float)($kr['total_points']??0));$score=$kpiRaw*0.25;$source='KPI Dapur · Sinkron · Bobot 25%';}}
  $row=['source_type'=>'assignment','assignment_id'=>(int)$a['assignment_id'],'bo_user_id'=>null,'person_id'=>(int)$a['person_id'],'employee_name'=>(string)$a['canonical_name'],'role_key'=>(string)$a['role_key'],'unit_type'=>$unitType,'system_key'=>$systemKey,'unit_name'=>(string)($us['unit_name']??$a['system_name']),'revenue_base'=>$rev,'payroll_percentage'=>$pct,'payroll_budget'=>$budget,'pool_percentage'=>$pct,'pool_amount'=>$budget,'incentive_pool'=>0.0,'kpi_raw'=>$kpiRaw,'kpi_target'=>$target,'kpi_score'=>$score,'kpi_source'=>$source,'base_salary'=>bo_payroll_money($es['base_salary']??0),'overtime'=>bo_payroll_money($es['overtime']??0),'bpjs_kesehatan'=>bo_payroll_money($es['bpjs_kesehatan']??0),'bpjs_ketenagakerjaan'=>bo_payroll_money($es['bpjs_ketenagakerjaan']??0),'punishment'=>bo_payroll_money($es['punishment']??$es['deduction']??0),'kasbon'=>bo_payroll_money($es['kasbon']??0),'notes'=>(string)($es['notes']??'')];$idx=count($items);$items[]=$row;$groups[$unitKey][]=$idx;
 }
 $boSetting=$unitSettings[bo_payroll_unit_key('backoffice','backoffice')]??['pool_percentage'=>0,'is_active'=>1,'unit_name'=>'Back Office'];if(!empty($boSetting['is_active']))foreach(bo_payroll_admin_rows() as $a){$es=$employeeSettings['admin:'.(int)$a['id']]??[];if(isset($es['is_eligible'])&&(int)$es['is_eligible']!==1)continue;$kr=$localKpi['backoffice'][(int)$a['id']]??null;$score=$kr?max(0,min(120,(float)$kr['final_score'])):0.0;$rev=(float)$financial['backoffice_revenue'];$pct=(float)($boSetting['pool_percentage']??0);$budget=round($rev*$pct/100,2);$row=['source_type'=>'backoffice_user','assignment_id'=>null,'bo_user_id'=>(int)$a['id'],'person_id'=>null,'employee_name'=>(string)$a['name'],'role_key'=>(string)$a['role_key'],'unit_type'=>'backoffice','system_key'=>'backoffice','unit_name'=>(string)($boSetting['unit_name']??'Back Office'),'revenue_base'=>$rev,'payroll_percentage'=>$pct,'payroll_budget'=>$budget,'pool_percentage'=>$pct,'pool_amount'=>$budget,'incentive_pool'=>0.0,'kpi_raw'=>$score,'kpi_target'=>100.0,'kpi_score'=>$score,'kpi_source'=>$kr?'KPI Back Office · Final':'Belum Final','base_salary'=>bo_payroll_money($es['base_salary']??0),'overtime'=>bo_payroll_money($es['overtime']??0),'bpjs_kesehatan'=>bo_payroll_money($es['bpjs_kesehatan']??0),'bpjs_ketenagakerjaan'=>bo_payroll_money($es['bpjs_ketenagakerjaan']??0),'punishment'=>bo_payroll_money($es['punishment']??$es['deduction']??0),'kasbon'=>bo_payroll_money($es['kasbon']??0),'notes'=>(string)($es['notes']??'')];$idx=count($items);$items[]=$row;$groups['backoffice:backoffice'][]=$idx;}

 $unitSummary=[];
 foreach($groups as $unitKey=>$indexes){$budget=(float)($items[$indexes[0]]['payroll_budget']??0);$fixed=0.0;$weightTotal=0.0;foreach($indexes as $i){$fixed+=(float)$items[$i]['base_salary']+(float)$items[$i]['overtime'];$weightTotal+=max(0,(float)$items[$i]['kpi_score']);}$incentivePool=max(0,round($budget-$fixed,2));foreach($indexes as $i){$w=max(0,(float)$items[$i]['kpi_score']);$incentive=$weightTotal>0?round($incentivePool*$w/$weightTotal,2):0.0;$items[$i]['incentive_pool']=$incentivePool;$items[$i]['kpi_weight']=$weightTotal>0?$w/$weightTotal:0.0;$items[$i]['incentive']=$incentive;$items[$i]['take_home']=round(max(0,$items[$i]['base_salary']+$items[$i]['overtime']+$incentive-$items[$i]['bpjs_kesehatan']-$items[$i]['bpjs_ketenagakerjaan']-$items[$i]['punishment']-$items[$i]['kasbon']),2);}
  $real=0.0;foreach($indexes as $i)$real+=(float)$items[$i]['take_home'];$unitSummary[$unitKey]=['unit_name'=>$items[$indexes[0]]['unit_name'],'unit_type'=>$items[$indexes[0]]['unit_type'],'revenue'=>$items[$indexes[0]]['revenue_base'],'percentage'=>$items[$indexes[0]]['payroll_percentage'],'budget'=>$budget,'fixed_gross'=>$fixed,'incentive_pool'=>$incentivePool,'realization'=>$real,'variance'=>$budget-$real,'over_budget'=>$fixed>$budget];
 }
 $tot=['base_salary'=>0.0,'overtime'=>0.0,'incentive'=>0.0,'bpjs_kesehatan'=>0.0,'bpjs_ketenagakerjaan'=>0.0,'punishment'=>0.0,'kasbon'=>0.0,'take_home'=>0.0,'budget'=>0.0];foreach($items as $it)foreach(['base_salary','overtime','incentive','bpjs_kesehatan','bpjs_ketenagakerjaan','punishment','kasbon','take_home'] as $k)$tot[$k]+=(float)($it[$k]??0);foreach($unitSummary as $u)$tot['budget']+=(float)$u['budget'];
 return ['month'=>$month,'items'=>$items,'totals'=>$tot,'unit_summary'=>$unitSummary,'financial'=>$financial,'kpi_errors'=>$kpiErrors,'financial_errors'=>$financial['errors']];
}

function bo_payroll_save_run(string $month,int $userId,bool $finalize=false): int {
 $calc=bo_payroll_compute($month);if($finalize&&(!empty($calc['financial_errors'])||!empty($calc['kpi_errors'])))throw new RuntimeException('Finalisasi dibatalkan karena sumber omset/KPI Dapur gagal dibaca.');if($finalize&&empty($calc['items']))throw new RuntimeException('Belum ada pegawai eligible.');if($finalize){foreach($calc['items'] as $it)if((float)$it['kpi_score']<=0||str_contains((string)$it['kpi_source'],'Belum Final'))throw new RuntimeException('Finalisasi dibatalkan karena masih ada KPI Toko/Back Office yang belum Final atau KPI Dapur belum tersedia.');}
 $existing=bo_exec('SELECT * FROM bo_payroll_runs WHERE payroll_month=? LIMIT 1',[$month])->fetch();if($existing&&in_array((string)$existing['status'],['final','paid'],true))throw new RuntimeException('Payroll bulan ini sudah dikunci.');bo_db()->beginTransaction();try{
  $snap=json_encode(['financial'=>$calc['financial'],'unit_summary'=>$calc['unit_summary'],'kpi_errors'=>$calc['kpi_errors'],'financial_errors'=>$calc['financial_errors']],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
  if($existing){$runId=(int)$existing['id'];bo_exec("UPDATE bo_payroll_runs SET status='draft',total_base_salary=?,total_incentive=?,total_allowance=0,total_overtime=?,total_bpjs_kesehatan=?,total_bpjs_ketenagakerjaan=?,total_punishment=?,total_kasbon=?,total_deduction=?,total_adjustment=0,total_take_home=?,snapshot_json=?,updated_by=?,updated_at=NOW() WHERE id=?",[$calc['totals']['base_salary'],$calc['totals']['incentive'],$calc['totals']['overtime'],$calc['totals']['bpjs_kesehatan'],$calc['totals']['bpjs_ketenagakerjaan'],$calc['totals']['punishment'],$calc['totals']['kasbon'],$calc['totals']['bpjs_kesehatan']+$calc['totals']['bpjs_ketenagakerjaan']+$calc['totals']['punishment']+$calc['totals']['kasbon'],$calc['totals']['take_home'],$snap,$userId,$runId]);bo_exec('DELETE FROM bo_payroll_items WHERE run_id=?',[$runId]);}
  else{bo_exec("INSERT INTO bo_payroll_runs(payroll_month,status,total_base_salary,total_incentive,total_allowance,total_overtime,total_bpjs_kesehatan,total_bpjs_ketenagakerjaan,total_punishment,total_kasbon,total_deduction,total_adjustment,total_take_home,snapshot_json,created_by,updated_by,created_at) VALUES(?,'draft',?,?,0,?,?,?,?,?,?,0,?,?,?,?,NOW())",[$month,$calc['totals']['base_salary'],$calc['totals']['incentive'],$calc['totals']['overtime'],$calc['totals']['bpjs_kesehatan'],$calc['totals']['bpjs_ketenagakerjaan'],$calc['totals']['punishment'],$calc['totals']['kasbon'],$calc['totals']['bpjs_kesehatan']+$calc['totals']['bpjs_ketenagakerjaan']+$calc['totals']['punishment']+$calc['totals']['kasbon'],$calc['totals']['take_home'],$snap,$userId,$userId]);$runId=(int)bo_db()->lastInsertId();}
  foreach($calc['items'] as $it){bo_exec("INSERT INTO bo_payroll_items(run_id,source_type,assignment_id,bo_user_id,person_id,employee_name_snapshot,role_key_snapshot,unit_type,system_key,unit_name_snapshot,revenue_base,payroll_budget,pool_percentage,pool_amount,incentive_pool,kpi_raw,kpi_target,kpi_score,kpi_weight,kpi_source,incentive_amount,base_salary,allowance,overtime,bpjs_kesehatan,bpjs_ketenagakerjaan,punishment,kasbon,deduction,adjustment,take_home,notes,snapshot_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,?,?,?,?, ?,0,?,?,?,NOW())",[$runId,$it['source_type'],$it['assignment_id'],$it['bo_user_id'],$it['person_id'],$it['employee_name'],$it['role_key'],$it['unit_type'],$it['system_key'],$it['unit_name'],$it['revenue_base'],$it['payroll_budget'],$it['pool_percentage'],$it['pool_amount'],$it['incentive_pool'],$it['kpi_raw'],$it['kpi_target'],$it['kpi_score'],$it['kpi_weight'],$it['kpi_source'],$it['incentive'],$it['base_salary'],$it['overtime'],$it['bpjs_kesehatan'],$it['bpjs_ketenagakerjaan'],$it['punishment'],$it['kasbon'],$it['bpjs_kesehatan']+$it['bpjs_ketenagakerjaan']+$it['punishment']+$it['kasbon'],$it['take_home'],$it['notes'],json_encode($it,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);}
  if($finalize)bo_exec("UPDATE bo_payroll_runs SET status='final',finalized_by=?,finalized_at=NOW(),updated_by=?,updated_at=NOW() WHERE id=?",[$userId,$userId,$runId]);bo_db()->commit();return $runId;
 }catch(Throwable $e){if(bo_db()->inTransaction())bo_db()->rollBack();throw $e;}
}
function bo_payroll_run(string $month): ?array {$r=bo_exec('SELECT * FROM bo_payroll_runs WHERE payroll_month=? LIMIT 1',[$month])->fetch();if(!$r)return null;$r['items']=bo_exec("SELECT * FROM bo_payroll_items WHERE run_id=? ORDER BY FIELD(unit_type,'store','dapur','backoffice'),unit_name_snapshot,employee_name_snapshot",[(int)$r['id']])->fetchAll()?:[];return $r;}
